### ISSUE TITLE
Feature request: a way to ensure certain tests are executed sequentially

### ISSUE THREAD

**Issue by mightybyte** [feuerbach/tasty#100]
I'm building some highly stateful tests that talk to an external database, and I need to ensure that the tests for it execute sequentially.  Would it be possible to create a combinator like this that executes the list of tests sequentially?

    testGroupSequential :: TestName -> [TestTree] -> TestTree

**Comment by feuerbach** [comment]
In my experience, for highly stateful, sequential tests you usually want this: http://hackage.haskell.org/package/tasty-hunit-0.9.1/docs/Test-Tasty-HUnit.html#v:testCaseSteps

**Comment by mightybyte** [comment]
That looks close to what I want.  However, in this particular case I'm using goldenVsFile from tasty-golden.  I need to run goldenVsFile multiple times to check multiple files that get generated sequentially based on results from the previous one.  Since that returns a TestTree it doesn't seem like it will work with testCaseSteps.

**Comment by feuerbach** [comment]
No, it won't.

The general problem of inter-test dependencies was being discussed in #48. In particular, `testGroupSequential` is expressible in terms of `runBefore`/`runAfter`.

**Comment by mightybyte** [comment]
It seems like another way to achieve this could be to make tasty-golden use HUnit.  Would that be possible?

I need to get this working ASAP, so I'm willing to work on a pull request.  What would be the best way forward?

**Comment by feuerbach** [comment]
I can see several workarounds. Can you describe what these tests are about? Are they open source? Each workaround has its own compromises, so it's hard to say in general.

The simplest one ­— we could change the scheduler so that when there's only one thread, the tests are run in strictly the same order as they appear in the tree. Would that work for you?

**Comment by mightybyte** [comment]
It's not an open source project, but the big picture is that I'm testing an ETL system that dumps data into a database.  So the whole thing is inherently stateful and I need control over the order in which these goldenVsFile calls run.  It's faster, simpler, and a better test of the system if I structure these tests so they depend on the state of the DB after the previous test case.

I guess strictly speaking that change would work for me.  However it feels fragile and doesn't give me great confidence, and on top of that the test suite already takes awhile to run, so parallelism is something we probably don't want to give up.  That being said, the fastest thing that gets us to a working system would be a good start.

**Comment by feuerbach** [comment]
One thing that you don't mention but I assume you do want is that when a test in such a group fails, further tests are not executed (because they depend on the side effects of this failed test, so chances are we're in an inconsistent state).

Tasty currently doesn't support such dependencies (this is the subject of #48). However, it's certainly possible within a single test (which I recently implemented in tasty-hunit).

You could do the same to tasty-golden. It'd be a bit more involved (because of the `--accept` command). Perhaps add a new case of a golden test that includes a list of primitive golden tests, and define corresponding operations for that case.

**Comment by mightybyte** [comment]
In the immediate term I don't care a great deal about whether subsequent tests execute or not.  I guess it might be nice to have the pipeline stop when one fails, but that's optional IMO.  What's more important to me is simply having the ability to define sequential test execution.

You solved it once with tasty-hunit, but as we've seen that doesn't apply to tasty-golden, so ultimately I think we should have a solution to this issue at the tasty level, not the provider level.

**Comment by feuerbach** [comment]
> What's more important to me is simply having the ability to define sequential test execution.

You can certainly pursue this direction if you want.

I can't promise that I'll include this code as part of tasty, but since it's in-house software, it shouldn't be a problem for you.

**Comment by mightybyte** [comment]
Ok, I'll figure something out and let you know what I come up with.

**Comment by mightybyte** [comment]
I refactored my tests to run everything up front and snapshot the external state at appropriate times, so it was possible for me to make it work without this.  However, if I had needed inter-test dependencies, I would have been stuck.  Closing this issue because #48 subsumes it.
