### ISSUE TITLE
testCaseSteps doesn't seem to report steps on failure

### ISSUE THREAD

**Issue by jberryman** [feuerbach/tasty#137]
I have a test of the form:

```
testCaseSteps "foo" $ \step -> do
      step "bar"
      p1 <- baz ...
```

And when an exception is thrown I don't get indication of the preceding steps (at least "bar" obviously should have been displayed):

```
    foo:                                                                 FAIL
      Exception: whatever

      blah
      ...
```

**Comment by feuerbach** [comment]
Confirmed, steps are only preserved for `assertFailure`, not for arbitrary exceptions.

**Comment by feuerbach** [comment]
If you need a quick workaround, you can build the package locally and replace HUnitFailure with SomeException. To figure out the correct fix, I've opened  #138.

**Comment by zoranbosnjak** [comment]
I have got the same problem. From the testrun output, I can not tell from which step the exception came from. How about changing a `step` function such that it takes complete step action as argument. Then it could catch all exceptions inside the step, not only `assertFailure`. This would change the type signature of the `testCaseSteps` function, but it seems that this would solve the problem.

The example from the documentation would then look something like this:
```
main = defaultMain $ testCaseSteps "Multi-step test" $ \step -> do
  result <- step "Preparing..." $ do
    -- do something (catch all exceptions)
    return "some result"

  -- do something between steps (catch only HUnitFailure)

  step "Running part 1" $ do
    -- do something (catch all exceptions)
    return ()

  step "Running part 2" $ case result of
      "wrong result 1" -> assertFailure "BAM!"
      "wrong result 2" -> fail "BAM!"
      _ -> do
        -- do something (catch all exceptions)
        return ()

  step "Running part 3" $ do
    -- do something (catch all exceptions)
    return ()
```
I am not familiar with the timeout problem as discussed in #138, but it seems to me that if the timer is set and it expires..., it is OK to catch this inside the step action, the same way as any other exception.
Maybe this kind of wrapping could fix a `testCaseSteps` function, so that it can always tell at which step the failure was (which is the main point of this function).

**Comment by michalrus** [comment]
Yes, so this `-1+1` does it:

```diff
diff --git a/hunit/Test/Tasty/HUnit/Steps.hs b/hunit/Test/Tasty/HUnit/Steps.hs
index 0852b69..ec9f994 100644
--- a/hunit/Test/Tasty/HUnit/Steps.hs
+++ b/hunit/Test/Tasty/HUnit/Steps.hs
@@ -28,7 +28,7 @@ instance IsTest TestCaseSteps where
 
         Right {} -> testPassed (unlines msgs)
 
-        Left (HUnitFailure errMsg) -> testFailed $
+        Left (SomeException ex) -> let errMsg = show ex in testFailed $
           if null msgs
             then
               errMsg
```

But it also recompiles the world in a moderately sized project. ;d
