### ISSUE TITLE
Job control

### ISSUE THREAD

**Issue by ezyang** [feuerbach/tasty#153]
@feuerbach asked me to describe my problem on GH, so here goes.

I recently wrote a new test runner for standalone hs files (https://github.com/haskell/cabal/tree/master/cabal-testsuite), which attempts to solve the edit-recompile problem by using GHCi to interpret test scripts, rather than forcing them to be collected and built together.

This in and of itself is not difficult for Tasty to handle: you just write some code to read the file system and generate the necessary test tree. However, I hit a snag: shelling out to runghc for each test script is too slow; to run lots of small tests quickly, I needed to create a persistent GHCi session per core and reuse it across tests. I couldn't figure out how to do this with tasty so I ended up writing my own test runner.

So, here were the requirements:

1. I need to read in the number of cores for the command line, and allocate that many GHCi processes. I then want tests to be evenly distributed across these processes (the most natural way of implementing this is each GHCi process is associated with a test runner thread which grabs the next test to be run and then runs it on its GHCi.)
2. I need Ctrl-C handling to work correctly, because I need to ensure GHCi processes get killed if someone interrupts the test handler. I wrote the code to do this here (https://github.com/haskell/cabal/blob/master/cabal-testsuite/main/cabal-tests.hs#L187); essentially, if the main thread gets an async exception, I need to cancel all of the GHCi threads, and *wait* for them to finish tearing down. 
3. Getting the GHCi interaction right (without deadlocking) took some time and in the meantime I ended up developing some logging infrastructure to get information from each of the running threads without interleaving the output. Tasty doesn't seem to have native logging capabilities so I'm not sure how that would look.

I posted about this on IRC and MarcelineVQ contributed some code which might do the trick http://lpaste.net/342512 but it's certainly not a complete solution; in particular, I'm not really sure how tasty's threading model works (does it create a new thread per test?)

**Comment by feuerbach** [comment]
Thanks for writing this up. Just to clarify: when you talk about CPUs, do you refer to the user-specified number of threads (`--threads`), or is there anything special about the physical number of cores in your use case?

**Comment by feuerbach** [comment]
Re 3), this is just for you to debug your code, not for the end users, right?

**Comment by ezyang** [comment]
> Thanks for writing this up. Just to clarify: when you talk about cores, do you refer to the user-specified number of threads

Yep, user-specified number (was using "cores" colloquially.)

> just for you to debug your code, not for the end users, right?

Yep!

**Comment by feuerbach** [comment]
Here's the rough design:

At the beginning, create a global TVar holding the list of ghc sessions and their total number. I suppose you can use a Resource to share this tvar across the worker threads.

Then you create a test tree where each test does the following:

1. If there is a free ghc session in the session list, pass a test filename to it (and temporarily remove it from the list).
2. If there isn't one, but the total number of created sessions is <= numThreads, create one. (The total number is also stored in the TVar.)
3. Otherwise, wait until a session is returned to the list. (Although this shouldn't happen, since tasty itself enforces the max number of workers.)

Re 2), I'll need to read the source to see how Ctrl-C is handled.

Re 3), how about writing your logs to a file or non-stdout file descriptor that can be redirected? Or what sort of logging capabilities are you looking for?

**Comment by feuerbach** [comment]
Not sure if there is interest anymore, so closing. Feel free to reopen or create more specific issues (Ctrl-C handling etc).
