### ISSUE TITLE
Timeout options not working.

### ISSUE THREAD

**Issue by schteeben95** [feuerbach/tasty#182]
![screen shot 2017-09-02 at 3 00 26 pm](https://user-images.githubusercontent.com/7964707/29993155-d08a6bba-8ff1-11e7-81d1-76328f5dc562.png)

As you can see above, the task was run with `--timeout=10s`, but it's been running for more than 6.5 minutes. I had to manually kill it off.

Is this a known issue?

**Comment by feuerbach** [comment]
No, not a known issue. It works in simple cases, so there must be something about your test suite that triggers this.

Can you reliably reproduce this? Can you try to make a minimal reproducible example?

**Comment by schteeben95** [comment]
```haskell
import Test.Tasty
import Test.Tasty.HUnit
import Test.Tasty.QuickCheck as QC

main = 
    defaultMain $
    testGroup "Recursion" [properties]

properties =
    testGroup
        "Q8Recursion Properties"
        [ QC.testProperty "makeYs" $ \x ->
            makeYs (x :: Integer) == replicate (fromIntegral x) 'Y'
          ]
          
makeYs :: Integer -> String
makeYs x
    | x <= 0        = ""
    | x >  0        = makeYs x
```

`ghc Test.hs -O2 && ./Test --timeout=5s`

This problem occurs when compiled with `-O2` or `-O`, but resolved with no `O` flags at all.

**Comment by feuerbach** [comment]
Ah, I see. Based on your observation re optimization flags and on the form of `makeYs`, I suspect the reason is that the `makeYs` loop runs without allocations, and therefore doesn't allow interruptions. See the first bullet point [here](https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/bugs.html#bugs-in-ghc). Indeed, if I recompile your code with `-fno-omit-yields`, the timeout is triggered as it should.

So yeah, I guess it is a know bug, but in ghc, not tasty. There's not much we can do about it in tasty, I'm afraid.
