### ISSUE TITLE
Feature request: Tweak the color-coding to highlight differences between "expected" and "but got"

### ISSUE THREAD

**Issue by EdmundsEcho** [feuerbach/tasty#226]
This is a great resource that improves my workflow.  Thank you!

Some of my outputs can get quite large.  Finding exactly where the test failed is currently a bit of a hand-eye exercise; hand being my finger to keep track of where the "expected" matches the "but go".  I use my finger to trace the output until I see the contrast.

![screen shot 2018-08-06 at 12 05 16 pm](https://user-images.githubusercontent.com/11245417/43727981-96a03616-9971-11e8-84f7-3f1b3d1a3d80.png)

It would be great if there was a feature that differentiated the output that is different between the two.  For instance, I have seen the use of green and red, where red tells me exactly where the differences are.

\- E

**Comment by feuerbach** [comment]
Hey @EdmundsEcho, I'm glad you find tasty useful.

I agree, that would be nice. It boils down to two things:

1. Figure out how 'got' and 'expected' things differ.
2. Highlight them with different colors.

(1) has a huge design space, so it's better solved by add-on packages, outside of tasty-core. For instance:

* tasty-golden can run diff (or even colordiff!) to show a diff between two files. This seems to be well-suited for your use case: use tasty-golden (as explained [here](https://ro-che.info/articles/2017-12-04-golden-tests)) together with a pretty-printer like aeson-pretty (to split the json over multiple lines) and tell tasty-golden to use diff/colordiff. 
* or one could use [gdiff](https://hackage.haskell.org/package/gdiff) or similar to perform a structural (instead of textual) diff
* I myself experimented with something similar: https://github.com/feuerbach/test-equal. I can't provide any support for that code, but you might find it useful and turn into a proper package.

Regarding the colors, that is (2), I think (but haven't tested) that colordiff or a similar method that would embed ANSI control sequences would just work. If it doesn't, we can talk about it separately.

**Comment by neongreen** [comment]
Note that `hspec` already does it (highlighting the diffing parts with red and green).

**Comment by benkolera** [comment]
I just wanted to document my steps that I took to remedy hunit's (not tasty's) unfriendliness here.

With the help of the following packages `pretty`, `pretty-show` and `Diff` I managed this hunit combinator that has a pretty high Power/Effort ratio. It may be useful to others also

```haskell
(@?~)
  :: (Eq a, Show a)
  => a
  -> a
  -> IO ()
got @?~ expected = assertBool (show diff) (got == expected)
  where
    gotPurdy = lines $ ppShow got
    expectedPurdy = lines $ ppShow expected
    diff = prettyContextDiff "Got" "Expected" Doc.text (getContextDiff 3 gotPurdy expectedPurdy)
```

Outputs something like this, which does really well for the structure that I have. It will look horrible for something that doesn't pretty print into multiple lines with ppShow though.

```
3rd Win moves to firing round:                        FAIL
          tests/Main.hs:384:
          --- Got
          +++ Expected
          @@
           Right
          -  ( Complete
          +  ( FiringRound
          @@
                 (fromList
                    [ ( PlayerId { unPlayerId = 1 }
                      , ( Player
          @@
                        )
                      )
                    ])
          -      (SideEffectsWin ThreeFailedProjects)
          @@
                 [ HistoricRoundState
                     { historicRoundShape =
                         RoundShape { roundShapeTeamSize = 2 , roundShapeTwoFails = False }
          @@
                 , HistoricRoundState
                     { historicRoundShape =
                         RoundShape { roundShapeTeamSize = 3 , roundShapeTwoFails = False }
          -          , historicRoundTeam =
          -              Just
          -                (fromList
          -                   [ PlayerId { unPlayerId = 1 }
          -                   , PlayerId { unPlayerId = 2 }
          -                   , PlayerId { unPlayerId = 3 }
          -                   ])
          +          , historicRoundTeam = Nothing
          @@
                     , historicRoundVotes = []
          -          , historicRoundResult = RoundFailure 1
          +          , historicRoundResult = RoundSuccess 1
          @@
                     }
                 ]
             , Nothing
          -  , Just
          -      (GameEnded
          -         (fromList
          -            [ ( PlayerId { unPlayerId = 1 }
          -              , ( Player
          -                    { playerId = PlayerId { unPlayerId = 1 } , playerName = "Player1" }
          -                , CompositionalCrusaders (Just FPExpert)
          -                )
          -              )
          -            , ( PlayerId { unPlayerId = 2 }
          -              , ( Player
          -                    { playerId = PlayerId { unPlayerId = 2 } , playerName = "Player2" }
          -                , SneakySideEffects (Just MiddleManager)
          -                )
          -              )
          -            , ( PlayerId { unPlayerId = 3 }
          -              , ( Player
          -                    { playerId = PlayerId { unPlayerId = 3 } , playerName = "Player3" }
          -                , CompositionalCrusaders Nothing
          -                )
          -              )
          -            , ( PlayerId { unPlayerId = 4 }
          -              , ( Player
          -                    { playerId = PlayerId { unPlayerId = 4 } , playerName = "Player4" }
          -                , CompositionalCrusaders Nothing
          -                )
          -              )
          -            , ( PlayerId { unPlayerId = 5 }
          -              , ( Player
          -                    { playerId = PlayerId { unPlayerId = 5 } , playerName = "Player5" }
          -                , SneakySideEffects Nothing
          -                )
          -              )
          -            ])
          -         (SideEffectsWin ThreeFailedProjects))
          +  , Just ThreeSuccessfulProjects
          @@
             )
```

Also, there was https://github.com/dag/HUnit-Diff/blob/master/Test/HUnit/Diff.hs which doesn't pretty print the show output and acts more like hspec.

I'm thinking of releasing a library that has both the ppShow and the character by character hunit combinators around. There's some additional goodies in https://github.com/dag/HUnit-Diff/pull/2/files that could be useful too so that you can mix and match based on what gives you the best error for your structure.  If this sounds useful to you and I haven't done it, just yell at me here. :smile: 

I didn't know till today that Hspec just uses Hunit under the hood anyway and catches the HUnit exceptions to pretty print them. I don't know if I like that, because I agree with @feuerbach that there is probably not a one size fits all here (a) structural gdiff is nice, but requires some effort on your behalf so not always better. b) Depending on whether your thing ppShows well or not, you may want a ppShow based line diff or a character by character one (like hspec's default).

FWIW it's worth to this information gathering, hspec uses the `Diff` package too with some extra escaping. http://hackage.haskell.org/package/hspec-core-2.7.1/docs/src/Test.Hspec.Core.Formatters.Diff.html

**Comment by EdmundsEcho** [comment]
@benkolera  I'm just seeing the response to my suggestion about a year ago now.  Thank you for sharing your high power/input code snippet.  Apologies for the question given the effort you put in, but what might be the quickest way to integrate that snippet into either of my hspec or tasty tests?

**Comment by benkolera** [comment]
@EdmundsEcho just copy the @?~ function from above and find the necessary imports. 

Here's a full module with all of the imports that you should be able to steal:

```haskell
import Data.Aeson(ToJSON,FromJSON,Value, encode, eitherDecode)
import Data.Algorithm.DiffContext (prettyContextDiff, getContextDiff)
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.Builder as TLB
import Test.Tasty (TestName, TestTree)
import Test.Tasty.HUnit (assertBool, testCase)
import qualified Text.PrettyPrint as Doc
import Text.Show.Pretty (ppShow)

-- The person that wrote this really should put it in a library...
-- https://github.com/feuerbach/tasty/issues/226#issuecomment-508868067
(@?~)
  :: (Eq a, Show a)
  => a
  -> a
  -> IO ()
got @?~ expected = assertBool (show diff) (got == expected)
  where
    gotPurdy = lines $ ppShow got
    expectedPurdy = lines $ ppShow expected
    diff = prettyContextDiff "Got" "Expected" Doc.text (getContextDiff 3 gotPurdy expectedPurdy)
```
