### ISSUE TITLE
documentup pattern documentation is incorrect

### ISSUE THREAD

**Issue by epsilonhalbe** [feuerbach/tasty#247]
according to do https://documentup.com/feuerbach/tasty#patterns

    -p test/foo*

should match, but yield a "Could not parse pattern". I guess this is due to #38 . 

The new pattern should be `-p '$0 == test && $1 ~ /^foo/`.
Is there a simple way to match only 01-09 of `test  A case` where

    testgroup.subgroup.test A case 01
     ...
    testgroup.subgroup.test A case  20
    testgroup.subgroup.test B case  01
     ...
    testgroup.subgroup.test B case 20

ideal would be something along the lines of `/test A* 0[1-9]/`
right now I have a workaround to `$3 ~ /A/ && $3 ~ / 0/`.

**Comment by feuerbach** [comment]
1. Thanks, will fix.
2. No, globs or regexes are not supported at the moment unfortunately.

**Comment by epsilonhalbe** [comment]
If I can help, I can send a PR - I didn't see the sources for the documentup site

**Comment by feuerbach** [comment]
Thanks — the doc is generated from README.md in the root directory.

**Comment by sjakobi** [comment]
I have a similar issue where I would like to use the pattern including a slash: `type-inference/failure`.

I also can't figure out how to workaround the slash-parsing issue by using awk expressions – better parse errors would be very useful here!

**Comment by feuerbach** [comment]
@sjakobi this should work, I think:

`-p '/type-inference\/failure/'`

The logic is that you have to enclose the pattern in `/.../` since it contains special characters, and then you need to escape the `/` in the standard way to avoid it being treated as the pattern delimiter.

As for the original issue, it seems like documentup is no longer updated from the README source, so there's probably nothing we can do here. I don't think we link to documentup anywhere, so just ignore it.

**Comment by sjakobi** [comment]
@feuerbach Thank you! This works if I use the test executable directly. It was `cabal` that mangled my `--test-options`: https://github.com/haskell/cabal/issues/6248.
