### ISSUE TITLE
Tasty.HUnit IO tests with console output produce test output even with the `--hide-successes` option

### ISSUE THREAD

**Issue by mfeliu** [feuerbach/tasty#261]
Hi everybody,

While running some tests with `IO` and `Tasty.HUnit` that produce console output I have found that test output was generated even with the `--hide-succeses` output. If you run them many times from the same `ghci` session, the behavior is unpredictable.

This is a small example that shows this behavior:
```
module Main where

import Test.Tasty.HUnit
import Test.Tasty

main :: IO ()
main = defaultMain $
  testGroup "Tests" [
    testGroup "Unit" [
      testGroup "Group" [
        testCase "paver_pave" $
          do
            putStrLn "Line 1"
            putStrLn "Line 2"
            putStrLn "Line 3"
            putStrLn "Line 4"
            return True
          @? "ERROR"
      ]
    ]
  ]
```
Do you think is possible to correct this behavior or will it be the price for using `IO` in tests?

Thank you.

**Comment by feuerbach** [comment]
Yes, `--hide-successes` only affects tasty's own output. There's nothing reasonable that we can do to prevent tests from doing their own I/O.

In general, you should avoid doing console output from tests even if you don't use `--hide-successes`, see the first item of the [faq](https://github.com/feuerbach/tasty#faq). Try using testCaseSteps instead of putStrLn.
